subscriptions:
  - name: kiali-ossm
    namespace: openshift-operators
    channel: stable
    version:  1.73.8
    source: redhat-operators
  - name: servicemeshoperator
    namespace: openshift-operators
    channel: stable
    version: 2.5.2-0
    source: redhat-operators
  - name: lvms-operator
    namespace: openshift-storage
    channel: stable-4.16
    version:  4.16.0
    source: redhat-operators
  - name: kubevirt-hyperconverged
    namespace: openshift-cnv
    channel: stable
    version:  4.16.0
    source: redhat-operators
  - name: rhods-operator
    namespace: redhat-ods-operator 
    channel: fast
    version: 2.11.0 e
    source: redhat-operators
  - name: web-terminal
    namespace: openshift-operators
    channel: fast
    version: 1.10.0
    source: redhat-operators

