apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http01
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-private-key
    server: https://acme-staging-v02.api.letsencrypt.org/directory 
    email: shanoian90@gmail.com
    solvers:
    - http01:
        ingress:
          ingressClassName: openshift-default
