apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: nested-ocp-agent-iso
  namespace: nested-openshift-os-images
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
spec:
  source:
    upload: {}
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: lvms-fast-ssd-pool