apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: master0-rootdisk
  namespace: nested-openshift-os-images
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
spec:
  source:
    blank: {}
  pvc:
    accessModes:
      - ReadWriteOnce
    storageClassName: lvms-fast-ssd-pool
    resources:
      requests:
        storage: 120Gi
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: master1-rootdisk
  namespace: nested-openshift-os-images
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true" 
spec:
  source:
    blank: {}
  pvc:
    accessModes:
      - ReadWriteOnce
    storageClassName: lvms-fast-ssd-pool
    resources:
      requests:
        storage: 120Gi
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: master2-rootdisk
  namespace: nested-openshift-os-images
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"  
spec:
  source:
    blank: {}
  pvc:
    accessModes:
      - ReadWriteOnce
    storageClassName: lvms-fast-ssd-pool
    resources:
      requests:
        storage: 120Gi
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: worker0-rootdisk
  namespace: nested-openshift-os-images
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
spec:
  source:
    blank: {}
  pvc:
    accessModes:
      - ReadWriteOnce
    storageClassName: lvms-fast-ssd-pool
    resources:
      requests:
        storage: 150Gi