apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: day2-operands-install 
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: 'day2/operators/operands'
    repoURL: https://github.com/Chanoian/homelab.git 
    targetRevision: main
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - Validate=false
    automated:
      prune: true
      selfHeal: true
