apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: day-2-apps-of-apps-operators
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: 'app-of-apps'
    repoURL: https://gitlab.consulting.redhat.com/telus-nephio/infra.git
    targetRevision: main
    directory:
      recurse: true
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - Validate=false
    automated:
      prune: true
      selfHeal: true
