apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: set-allocatable
  namespace: openshift-config-operator
spec:
  machineConfigPoolSelector:
    matchLabels:
      node-role.kubernetes.io/master: "" 
  kubeletConfig:
    systemReserved:
      cpu: 1Gi                                                                 # change the CPU if needed
      memory: 2512Mi                                                            # change the memory if needed
