---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: master0-rootdisk
  namespace: nested-cluster
spec:
  source:
    blank: {}
  storage:
    storageClassName: lvms-fast-ssd-pool
    resources:
      requests:
        storage: 120Gi
    accessModes:
    - ReadWriteOnce
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: master1-rootdisk
  namespace: nested-cluster
spec:
  source:
    blank: {}
  storage:
    storageClassName: lvms-fast-ssd-pool
    resources:
      requests:
        storage: 120Gi
    accessModes:
    - ReadWriteOnce
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: master2-rootdisk
  namespace: nested-cluster
spec:
  source:
    blank: {}
  storage:
    storageClassName: lvms-fast-ssd-pool
    resources:
      requests:
        storage: 120Gi
    accessModes:
    - ReadWriteOnce
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: worker0-rootdisk
  namespace: nested-cluster
spec:
  source:
    blank: {}
  storage:
    storageClassName: lvms-fast-ssd-pool
    resources:
      requests:
        storage: 200Gi
    accessModes:
    - ReadWriteOnce