apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/Chanoian/homelab.git
    targetRevision: main
    path: clusters/main/infra
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Validate=false
      - SkipDryRunOnMissingResource=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
